version: '3'

services:
  squeue-db:
    image: mariadb
    volumes:
      - squeue-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=squeue
      - MYSQL_DATABASE=squeue
      - MYSQL_USER=squeue
      - MYSQL_PASSWORD=squeue
  squeue:
    build: .
    volumes:
      - .:/app
    environment:
      - SQUEUE_USERNAME=squeue
      - SQUEUE_PASSWORD=squeue
      - SQUEUE_HOSTNAME=squeue-db
      - SQUEUE_DATABASE=squeue
      - UPDATE_SQUEUE_LOGLEVEL=DEBUG
      - SQUEUE_COMMAND=/app/test/squeue
    links:
      - squeue-db
    depends_on:
      - squeue-db

volumes:
  squeue-data: